#!/usr/bin/env python3
"""
Script 4: Quantitative Results Bar Chart

Grouped bar chart comparing methods across terrain types.
Reads data from CSV files generated by extract_table_data.py.

Usage:
    python plot_bar_comparison.py --csv figures/comparison_success_rate.csv
    python plot_bar_comparison.py --csv figures/comparison_traverse_rate.csv
"""

import argparse
import csv
import numpy as np
import matplotlib.pyplot as plt

from plot_utils import (
    apply_style, COLORS, METHOD_NAMES, TERRAIN_NAMES_DISPLAY, TERRAIN_ORDER,
    save_figure,
)


OUTPUT_DIR = './figures'
OUTPUT_STEM = 'bar_comparison'

COMPARISON_METHODS = ['ours', 'depth_baseline', 'attn_baseline']


def plot_bar_comparison(
    results_mean: dict,
    results_std: dict = None,
    terrain_order: list = None,
    ylabel: str = 'Success Rate (%)',
):
    if terrain_order is None:
        terrain_order = TERRAIN_ORDER
    if results_std is None:
        results_std = {}

    method_keys = [k for k in results_mean if k in COLORS]
    n_methods = len(method_keys)
    n_terrains = len(terrain_order)

    fig, ax = plt.subplots(figsize=(5.5, 3.0))

    bar_width = 0.7 / max(n_methods, 1)
    x = np.arange(n_terrains)

    for i, mk in enumerate(method_keys):
        vals = np.array(results_mean[mk])
        offset = (i - n_methods / 2 + 0.5) * bar_width
        yerr = np.array(results_std[mk]) if mk in results_std else None

        bars = ax.bar(
            x + offset, vals, bar_width,
            label=METHOD_NAMES.get(mk, mk),
            color=COLORS[mk],
            edgecolor='white', linewidth=0.5,
            yerr=yerr,
            capsize=3 if yerr is not None else 0,
            error_kw={'linewidth': 0.8},
        )

        for j, (bar, val) in enumerate(zip(bars, vals)):
            if val > 0:
                y_top = bar.get_height()
                if yerr is not None:
                    y_top += yerr[j]
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    y_top + 0.8,
                    f'{val:.1f}',
                    ha='center', va='bottom', fontsize=8,
                )

    terrain_labels = [TERRAIN_NAMES_DISPLAY.get(t, t) for t in terrain_order]
    ax.set_xticks(x)
    ax.set_xticklabels(terrain_labels)
    ax.set_ylabel(ylabel)
    ax.set_ylim(bottom=0)
    ax.legend(loc='upper right', fontsize=8)
    fig.tight_layout()
    return fig


def load_csv(csv_path: str):
    means = {}
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        terrain_keys = [c for c in reader.fieldnames if c != 'method']
        for row in reader:
            mk = row['method']
            means[mk] = [float(row[t]) for t in terrain_keys]
    return means, terrain_keys


def parse_args():
    p = argparse.ArgumentParser(description='Grouped bar chart of results.')
    p.add_argument('--csv', type=str, required=True, help='Path to CSV with results')
    p.add_argument('--ylabel', type=str, default='Value (%)')
    p.add_argument('--output', type=str, default=None)
    return p.parse_args()


def main():
    apply_style()
    args = parse_args()

    results_mean, terrain_order = load_csv(args.csv)
    fig = plot_bar_comparison(results_mean, terrain_order=terrain_order, ylabel=args.ylabel)
    save_figure(fig, args.output or OUTPUT_STEM, OUTPUT_DIR)
    plt.close(fig)


if __name__ == '__main__':
    main()
